dist: xenial
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8-dev'
  - 'nightly'
  - 'pypy'
  - 'pypy3.5'

stages:
  - lint
  - test
  - name: deploy
    if: tag is present

matrix:
  include:
    - stage: lint
      name: flake8
      python: '3.7'
    - stage: deploy
      name: Deploy to PyPI
      python: '3.7'
      install: skip
      script: skip
  allow_failures:
    - python: '3.8-dev'
    - python: 'nightly'

install:
  - pip install tox-travis

script:
  - tox

deploy:
  provider: pypi
  distributions: sdist
  user: 'Your username'
  password:
    secure: 'Your encrypted password'
  on:
    condition: $TRAVIS_BUILD_STAGE_NAME = Deploy
    tags: true
